arena_sunset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Administração | Arena Sunset'

urlpatterns = [
  path('admin/', admin.site.urls),

  path('backend/', include('backend.urls')),
  path('', include('frontend.urls')),
] + static(settings.UPLOAD_URL, document_root=settings.UPLOAD_ROOT)

backend/urls.py
from django.urls import path
from .views import *

app_name = 'backend'
urlpatterns = [
  path('grupos/buscar', GrupoView.as_view(http_method_names=['get']), name="Ver os grupos"),

  path('usuarios/ver/<int:id>', UsuarioCRUDView.as_view(http_method_names=['get']), name="Ver usuário"),
  path('usuarios/criar', UsuarioCRUDView.as_view(http_method_names=['post']), name="Criar usuário"),
  path('usuarios/atualizar/<int:id>', UsuarioCRUDView.as_view(http_method_names=['put']), name="atualizar usuário"),
  path('usuarios/ativar_desativar/<int:id>', UsuarioAtivacaoView.as_view(http_method_names=['put']), name="Ativar/desativar usuário"),
  path('usuarios/deletar/<int:id>', UsuarioCRUDView.as_view(http_method_names=['delete']), name="Deletar usuário"),
  path('usuarios/buscar', UsuarioCRUDView.as_view(http_method_names=['get']), name="Buscar usuários"),
  path('usuarios/trocar_senha', UsuarioSenhaView.as_view(http_method_names=['put']), name="Trocar senha de usuário"),
  path('usuarios/foto/gravar/<int:id>', UsuarioFotoView.as_view(http_method_names=['post']), name="Gravar imagem do usuário"),
  path('usuarios/foto/deletar/<int:id>', UsuarioFotoView.as_view(http_method_names=['delete']), name="Deletar imagem do usuário"),

  path('professores/listar', ProfessorView.as_view(http_method_names=['get']), name="Listar os professores"),

  path('alunos/ativar_desativar/<int:id>', AlunoAtivacaoView.as_view(http_method_names=['put']), name="Ativar/desativar aluno"),
  path('alunos/ver/<int:id>', AlunoView.as_view(http_method_names=['get']), name="Ver aluno"),
  path('alunos/listar', AlunoView.as_view(http_method_names=['get']), name="Buscar alunos"),
  path('alunos/contratantes', ContratanteView.as_view(http_method_names=['get']), name="Buscar alunos contratantes/pagantes"),
  path('alunos/criar', AlunoView.as_view(http_method_names=['post']), name="Criar aluno"),
  path('alunos/atualizar/<int:id>', AlunoView.as_view(http_method_names=['put']), name="Atualizar aluno"),
  path('alunos/deletar/<int:id>', AlunoView.as_view(http_method_names=['delete']), name="Deletar aluno"),
  path('alunos/<int:id>/pacotes/buscar', AlunoPacoteView.as_view(http_method_names=['get']), name="Buscar os pacotes do aluno"),

  path('pacotes/ativar_desativar/<int:id>', PacoteAtivacaoView.as_view(http_method_names=['put']), name="Ativar/desativar pacote"),
  path('pacotes/ver/<int:id>', PacoteCrudView.as_view(http_method_names=['get']), name="Ver pacote"),
  path('pacotes/criar', PacoteCrudView.as_view(http_method_names=['post']), name="Criar pacote"),
  path('pacotes/atualizar/<int:id>', PacoteCrudView.as_view(http_method_names=['put']), name="Atualizar pacote"),
  path('pacotes/deletar/<int:id>', PacoteCrudView.as_view(http_method_names=['delete']), name="Deletar pacote"),
  path('pacotes/listar', PacoteCrudView.as_view(http_method_names=['get']), name="Buscar pacotes"),
  path('pacotes/<int:id>/contratos/buscar', PacoteAlunoView.as_view(http_method_names=['get']), name="Buscar contratos do pacote"),
  path('pacotes/<int:id>/contratar', PacoteAlunoView.as_view(http_method_names=['post']), name="Contratar pacote"),
  path('pacotes/cancelar_contrato/<int:contrato>', PacoteAlunoView.as_view(http_method_names=['put']), name="Cancelar contrato"),

  path('agenda/buscar', AgendaView.as_view(http_method_names=['get']), name="Buscar reservas"),
  path('agenda/verificar_vencidos', JobView.as_view(http_method_names=['get']), name="Verificar vencidos"),

  path('agenda/reserva_especial/ver/<int:id>', ReservaEspecialCrudView.as_view(http_method_names=['get']), name="Ver reserva especial"),
  path('agenda/reserva_especial/criar', ReservaEspecialCrudView.as_view(http_method_names=['post']), name="Criar reserva especial"),
  path('agenda/reserva_especial/deletar/<int:id>', ReservaEspecialCrudView.as_view(http_method_names=['delete']), name="Deletar reserva especial"),

  path('agenda/reserva_unica/ver/<int:id>', ReservaUnica.as_view(http_method_names=['get']), name="Ver reserva única"),
  path('agenda/reserva_unica/criar', ReservaUnica.as_view(http_method_names=['post']), name="Criar reserva única"),
  path('agenda/reserva_unica/cancelar/<int:id>', ReservaUnica.as_view(http_method_names=['put']), name="Cancelar reserva única"),

  path('agenda/reserva_normal/ver/<int:id>', ReservaNormal.as_view(http_method_names=['get']), name="Ver reserva normal"),
  path('agenda/reserva_normal/criar', ReservaNormal.as_view(http_method_names=['post']), name="Criar reserva normal"),
  path('agenda/reserva_normal/cancelar/<int:id>', ReservaNormal.as_view(http_method_names=['put']), name="Cancelar reserva normal"),
  
]

frontend/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'frontend'
urlpatterns = [
  path('', views.index, name="index"),
  path('login', views.logar_usuario, name="login"),
  path('logout', views.deslogar, name="logout"),

  path('usuarios', views.criar_usuario_view, name="Usuários"),
  path('pacotes', views.criar_pacotes_view, name="Pacotes"),
  path('alunos', views.criar_alunos_view, name="Alunos"),

]

frontend/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages            

from backend.functions import (f_usuario_possui_grupo, f_nome_usuario)

def f_default_context(user):
  superusuario = user.is_superuser
  context = {
    'perfil_administrador': f_usuario_possui_grupo(user, 'ADM_SITE') or superusuario,
    'perfil_atendimento': f_usuario_possui_grupo(user, 'ATENDIMENTO'),
    'perfil_professor': f_usuario_possui_grupo(user, 'PROFESSOR'),
    'perfil_aluno': f_usuario_possui_grupo(user, 'ALUNO'),
  }
  return context

@login_required(login_url="/login")
def index(request):
  context = f_default_context(request.user)
  return render(request, 'frontend/index.html', context)

def logar_usuario(request):
  context = f_default_context(request.user)
  next_url = request.GET.get('next', '/')

  if request.method == 'POST':
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)

      nome = f_nome_usuario(user)
      
      messages.info(request, "Seja bem-vindo {}!".format(nome))
      return HttpResponseRedirect(next_url)
    else:
      context['erro_login'] = 'As credenciais informadas não são compatíveis!'
      return render(request, 'frontend/login.html', context)
    
  if request.user.is_authenticated:
    return HttpResponseRedirect('/')
  
  context['next_url'] = next_url
  return render(request, 'frontend/login.html', context)

def deslogar(request):
  logout(request)
  return HttpResponseRedirect('/')

@login_required(login_url="/login")
def criar_usuario_view(request):
  context = f_default_context(request.user)

  if context['perfil_administrador']:
    return render(request, 'frontend/usuarios.html', context)
  else:
    messages.error(request, "Você não possui acesso para o módulo de administração!")
    return HttpResponseRedirect('/')

@login_required(login_url="/login")
def criar_pacotes_view(request):
  context = f_default_context(request.user)

  if context['perfil_administrador']:
    return render(request, 'frontend/pacotes.html', context)
  else:
    messages.error(request, "Você não possui acesso para o módulo de administração!")
    return HttpResponseRedirect('/')

@login_required(login_url="/login")
def criar_alunos_view(request):
  context = f_default_context(request.user)

  if context['perfil_administrador'] or context['perfil_professor'] or context['perfil_atendimento']:
    return render(request, 'frontend/alunos.html', context)
  else:
    messages.error(request, "Você não possui acesso para o módulo de criação de alunos!")
    return HttpResponseRedirect('/')

frontend/templates/frontend/alunos.html
{% extends "frontend/template.html" %}
{% load static %}

{% block title %} Alunos | Arena Sunset {% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'frontend/css/alunos.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'frontend/css/libs/select2.css' %}">

<script src="{% static 'frontend/js/libs/jquery.mask.min.js' %}"></script>
<script src="{% static 'frontend/js/libs/select2.js' %}"></script>
<script src="{% static 'frontend/js/libs/select2.min.js' %}"></script>

<script src="{% static 'frontend/js/alunos.js' %}"></script>

<div class="card custom-cards mt-4 mb-4 me-3 ms-3">
  <div class="card-body">
    <div class="header_card">
      <h5>Alunos</h5>
      <button class="btn btn-new" id="new_aluno" type="button">Novo Aluno</button>
    </div>

    <div class="table tabela_dados  table-aluno mt-3">
      <table id="datatable-aluno" class="table table-dark table-responsive display nowrap"
        aria-describedby="table-aluno">
        <thead>
          <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Email</th>
            <th>Celular</th>
            <th>Status</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

  </div>
</div>

<div class="modal fade" id="modal-form" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Criação de Alunos</h1>
        <button type="button" class="btn-fechar close-modal" data-bs-dismiss="modal" aria-label="Close">
          <i class="fa-solid fa-xmark"></i>
        </button>
      </div>

      <div class="modal-body">
        <form class="formulario" enctype="multipart/form-data">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="nome" class="form-label"><b>Nome</b></label>
              <input id="nome" class="form-control" type="text" name="nome" placeholder="Digite o Nome" required
                maxlength="50">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="cpf" class="form-label"><b>CPF</b></label>
              <input id="cpf" class="form-control" type="text" name="cpf" placeholder="Digite o CPF">
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="data_nasc" class="form-label"><b>Data de Nascimento</b></label>
              <input id="data_nasc" class="form-control" type="date" name="data_nasc"
                placeholder="Digite a Data de Nascimento">
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="sexo" class="form-label"><b>Sexo</b></label>
              <select id="sexo" class="form-control" style="width: 100%">
                <option selected disabled>Selecione o Sexo</option>
                <option value="M">Masculino</option>
                <option value="F">Feminino</option>
              </select>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="email" class="form-label"><b>Email</b></label>
              <input id="email" class="form-control" type="email" name="email" placeholder="Digite o Email"
                maxlength="50">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="celular" class="form-label"><b>Celular</b></label>
              <input id="celular" class="form-control" type="text" name="celular" placeholder="Digite o Celular">
            </div>
          </div>
          {% csrf_token %}
        </form>

        <div id="error-message" class="text-danger mt-2"></div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-back close-modal" data-bs-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-new" id="Gravar" value="-1">Gravar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-plans" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Vínculo de Alunos e Pacotes</h1>
        <button type="button" class="btn-fechar close-modal" data-bs-dismiss="modal" aria-label="Close">
          <i class="fa-solid fa-xmark"></i>
        </button>
      </div>

      <div class="modal-body">
        <form class="formulario" enctype="multipart/form-data">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="aluno_nome" class="form-label"><b>Nome</b></label>
              <input id="aluno_nome" class="form-control" type="text" name="nome" placeholder="Nome" required disabled>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <label for="contratacao" class="form-label"><b>Data de Contratação</b></label>
              <input id="contratacao" class="form-control" type="date" name="Data de Contratação" required>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb-2">
              <label for="pacotes" class="form-label"><b>Pacotes</b></label>
              <select id="pacotes" class="form-control" name="pacotes" required style="width: 100%">
                <option selected disabled>Selecione o Pacote</option>
              </select>
            </div>
          </div>
        </form>

        <div id="error-message-pacotes" class="text-danger mt-2"></div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-back close-modal" data-bs-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-new" id="GravarVinculo" value="-1">Gravar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-view" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5"></h1>
        <button type="button" class="btn-fechar close-modal" data-bs-dismiss="modal" aria-label="Close">
          <i class="fa-solid fa-xmark"></i>
        </button>
      </div>

      <div class="modal-body">
        <fieldset>
          <legend>Dados do Usuário</legend>
          <div class="row divRowView" id="user-data">
            <!-- Campos de dados do usuário serão adicionados aqui -->
          </div>
        </fieldset>

        <fieldset class="mt-4">
          <legend>Plano Atual</legend>
          <div class="row divRowView" id="current-plan">
            <!-- Campos do plano atual serão adicionados aqui -->
          </div>
        </fieldset>

        <fieldset class="mt-4">
          <legend>Histórico</legend>
          <div class="row divRowView" id="history">
            <!-- Campos do histórico serão adicionados aqui -->
          </div>
        </fieldset>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-back close-modal" data-bs-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-new" id="Gravar" value="-1">Gravar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

frontend/templates/frontend/login.html
{% extends "frontend/template.html" %}
{% load static %}

{% block title %} Login | Arena Sunset {% endblock %}

{% block navbar %}{% endblock %}
{% block sidebar %}{% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'frontend/css/login.css' %}">
<script src="{% static 'frontend/js/login.js' %}"></script>

<div class="container-fluid login-container">

  <div class="card">
    <div class="card-title mt-4 mb-4">
      <img src="{% static 'frontend/img/logopadel.png' %}" alt="logo_padel" />
    </div>

    <div class="card-body">
      <form class="formulario" method="post" action="{% url 'frontend:login' %}?next={{next_url}}">
        {% csrf_token %}

        <div class="mb-3">
          <input class="form-control" type="text" name="username" placeholder="Usuário" required>
        </div>

        <div class="mb-3">
          <input class="form-control" type="password" autocomplete="current-password" name="password"
            placeholder="Senha" required>
        </div>

        <div class="mb-3">
          <button class="btn btn-new btn-login w-100" type="submit" value="login">Entrar</button>
        </div>

        <div id="error-message" class="text-danger mt-2">{{erro_login}}</div>

      </form>
    </div>
  </div>

</div>

{% endblock %}

frontend/templates/frontend/pacotes.html
{% extends "frontend/template.html" %}
{% load static %}

{% block title %} Pacotes | Arena Sunset {% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'frontend/css/pacotes.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'frontend/css/libs/select2.css' %}">

<script src="{% static 'frontend/js/libs/jquery.mask.min.js' %}"></script>
<script src="{% static 'frontend/js/libs/select2.js' %}"></script>
<script src="{% static 'frontend/js/libs/select2.min.js' %}"></script>
<script src="{% static 'frontend/js/pacotes.js' %}"></script>

<div class="card custom-cards mt-4 mb-4 me-3 ms-3">
  <div class="card-body">
    <div class="header_card">
      <h5>Pacotes de Aula</h5>
      <button class="btn btn-new" id="new_plan" type="button">Novo Pacote</button>
    </div>

    <div class="table tabela_dados table-plans mt-3">
      <table id="datatable-plan" class="table table-dark table-responsive display nowrap" aria-describedby="table-plan">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Qtd. Aulas</th>
            <th>Qtd. Participantes</th>
            <th>Valor</th>
            <th>Status</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

  </div>
</div>

<div class="modal fade" id="modal-form" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Criação de Pacotes</h1>
        <button type="button" class="btn-fechar close-modal" data-bs-dismiss="modal" aria-label="Close"><i
            class="fa-solid fa-xmark"></i></button>
      </div>

      <div class="modal-body">

        <form class="formulario" id="formulario" enctype="multipart/form-data">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <input id="nome" class="form-control" type="text" name="nome" placeholder="Nome do Pacote" required
                maxlength="50">
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <div class="input-group">
                <span class="input-group-text" id="addon_valor">R$</span>
                <input id="valor" class="form-control" type="text" name="valor" placeholder="Valor"
                  aria-describedby="addon_valor" required maxlength="20">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <select id="qtd_aulas" class="form-control" name="qtd_aulas" style="width: 100%" required>
                <option selected disabled>Aulas Semanais</option>
                <option value="1">Uma Aula</option>
                <option value="2">Duas Aulas</option>
                <option value="3">Três Aulas</option>
                <option value="4">Quatro Aulas</option>
                <option value="5">Cinco Aulas</option>
                <option value="6">Seis Aulas</option>
                <option value="7">Sete Aulas</option>
              </select>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-2">
              <select id="qtd_participantes" class="form-control" name="participantes" style="width: 100%" required>
                <option selected disabled>Participantes</option>
                <option value="1">Individual</option>
                <option value="2">Duplas</option>
                <option value="3">Trios</option>
                <option value="4">Quartetos</option>
              </select>
            </div>
          </div>

          {% csrf_token %}

        </form>

        <div id="error-message" class="text-danger mt-2"></div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-back close-modal" data-bs-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-new" id="Gravar" value="-1">Gravar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

frontend/templates/frontend/template.html
{% load static %}
<html lang="pt_br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Arena Sunset - Agenda" />
  <meta property="og:url" content="http://plataforma.arenasunsetpadel.com.br/" />
  <meta property="og:image" content="{% static 'frontend/img/logopadel.png' %}" />

  <link rel="shortcut icon" href="{% static 'frontend/img/favicon.ico' %}" type="image/x-icon">

  <link rel="stylesheet" type="text/css" href="{% static 'frontend/css/libs/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'frontend/css/libs/all.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'frontend/css/libs/datatables.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'frontend/css/template.css' %}">

  <script src="{% static 'frontend/js/libs/jquery.js' %}"></script>

  <script src="{% static 'frontend/js/libs/all.min.js' %}"></script>
  <script src="{% static 'frontend/js/libs/popper.js' %}"></script>
  <script src="{% static 'frontend/js/libs/bootstrap.js' %}"></script>
  <script src="{% static 'frontend/js/libs/datatables.min.js' %}"></script>

  <script src="{% static 'frontend/js/template.js' %}"></script>
  <script src="{% static 'frontend/js/init.js' %}"></script>

  <title>{% block title %}{% endblock %}</title>

</head>

<body>

  <main>
    {% block sidebar %}
    <nav class="custom-sidebar show" aria-label="sidebar">

      <div class="sidebar-header">
        <a class="btn-logo" href="/" title="Logo Arena Sunset">
          <img class="logo-nav" src="{% static 'frontend/img/logopadel.png' %}" alt="Logo Arena Sunset" />
        </a>

        <button class="navbar-toggler btn-toggle" type="button" title="Barra Lateral" id="btn-toggle-sidebar">
          <i class="icons fa-solid fa-x"></i>
        </button>
      </div>

      <div class="sidebar-body">
        <ul class="Btn-list">
          <li>
            <a class="btn-list-sidebar btn-list-sidebar-active" href="/">
              <i class="icons fa-solid fa-calendar-days"></i>
              <span class="list-title">Agenda</span>
            </a>
          </li>

          {% if perfil_administrador %}
          <li>
            <a class="btn-list-sidebar" href="{% url 'frontend:Alunos' %}">
              <i class="icons fa-solid fa-users"></i>
              <span class="list-title">Alunos</span>
            </a>
          </li>

          <li>
            <a class="btn-list-sidebar" href="{% url 'frontend:Pacotes' %}">
              <i class="icons fa-solid fa-address-card"></i>
              <span class="list-title">Pacotes</span>
            </a>
          </li>

          <li>
            <a class="btn-list-sidebar" href="{% url 'frontend:Usuários' %}">
              <i class="icons fa-solid fa-clipboard-user"></i>
              <span class="list-title">Colaboradores</span>
            </a>
          </li>
          {% endif %}

          {% if perfil_atendimento or perfil_professor %}
          <li>
            <a class="btn-list-sidebar" href="{% url 'frontend:Alunos' %}">
              <i class="icons fa-solid fa-users"></i>
              <span class="list-title">Alunos</span>
            </a>
          </li>
          {% endif %}

        </ul>
      </div>

    </nav>
    {% endblock %}

    <div class="page-wrapper" id="content">

      {% block navbar %}
      <nav id="navbar" class="navbar navSideOpen" data-bs-theme="dark" aria-label="navbar">

        <button class="navbar-toggler btn-toggle" type="button" title="Barra Lateral" id="btn-toggle-nav">
          <i class="icons fa-solid fa-x"></i>
        </button>

        <div class="btn-group me-3">

          <a class="myaccount dropdown-toggle" id="myaccount" role="button" data-bs-toggle="dropdown"
            aria-expanded="false" title="Minha Conta">
            <i class="fa-solid fa-user"></i>
          </a>

          <ul class="dropdown-menu">
            {% if user.is_authenticated %}

            <li>
              <span style="margin-left: 15px;">{{ user.get_full_name }}</span>
            </li>

            <li>
              <form method=" post" style="margin-bottom: 0;" action="{% url 'frontend:logout' %}">
                {% csrf_token %}
                <button class="dropdown-item" type="submit">Sair</button>
              </form>
            </li>

            {% else %}
            <li>
              <a class="dropdown-item" target="_self" href="{% url 'frontend:login' %}">Acessar</a>
            </li>
            {% endif %}
          </ul>

        </div>
      </nav>
      {% endblock %}

      <section class="container-fluid text-center" id="contentDiv">

        {% block content %}
        {% endblock %}

        <div class="modal fade" id="alertavel" tabindex="-1" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Aviso</h1>
                <button type="button" class="btn-fechar close-modal" data-bs-dismiss="modal" aria-label="Close"><i
                    class="fa-solid fa-xmark"></i></button>
              </div>
              <div class="modal-body">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-back close-modal" data-bs-dismiss="modal">Fechar</button>
              </div>
            </div>
          </div>
        </div>

      </section>

    </div>
  </main>

  <footer>
    {% if messages %}
    <div id="div_mensagens">
      <ul class="messages">
        {% for message in messages %}
        {% if message.tags == 'success' %}
        <li class="alert alert-success alert-dismissible">
          {% elif message.tags == 'info' %}
        <li class="alert alert-info alert-dismissible">
          {% elif message.tags == 'warning' %}
        <li class="alert alert-warning alert-dismissible">
          {% elif message.tags == 'error' %}
        <li class="alert alert-danger alert-dismissible">
          {% endif %}
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </footer>

  <script>
    removerAlertas()
  </script>
</body>

</html>